TestCases: 1,2
Browser: chrome
OS: Windows
TestCasesPath: C:\\Users\\kguttiko\\Documents\\GitHub\\keyword-driven-framework\\src\\main\\resources\\TestData\\TestCases.xlsx
BrowserDriverPath: C:\\Users\\kguttiko\\Documents\\GitHub\\keyword-driven-framework\\Drivers\\chromedriver.exe
screenshotspath: C:\\Users\\kguttiko\\Documents\\GitHub\\keyword-driven-framework\\Screenshots