TestCases: 1-100
Browser: chrome
OS: Windows
TestCasesPath: C:\Flogo\Project\Keyword-Driven-Framework\src\main\resources\TestData\TestCases.xlsx
BrowserDriverPath: C:\Flogo\Project\Keyword-Driven-Framework\Drivers\chromedriver.exe